# Created with https://github.com/dart-lang/mono_repo
language: dart

jobs:
  include:
    - stage: analyze
      script: ./tool/travis.sh dartanalyzer_0
      env: PKG="alryne"
      dart: dev
    - stage: format
      script: ./tool/travis.sh dartfmt
      env: PKG="alryne"
      dart: dev
    - stage: unit_test
      script: ./tool/travis.sh command_0
      env: PKG="alryne"
      dart: dev
    - stage: analyze
      script: ./tool/travis.sh dartanalyzer_1
      env: PKG="alryne_mobile"
      dart: dev
    - stage: format
      script: ./tool/travis.sh dartfmt
      env: PKG="alryne_mobile"
      dart: dev
    - stage: analyze
      script: ./tool/travis.sh dartanalyzer_1
      env: PKG="alryne_server"
      dart: dev
    - stage: format
      script: ./tool/travis.sh dartfmt
      env: PKG="alryne_server"
      dart: dev
    - stage: analyze
      script: ./tool/travis.sh dartanalyzer_2
      env: PKG="alryne_web"
      dart: dev
    - stage: format
      script: ./tool/travis.sh dartfmt
      env: PKG="alryne_web"
      dart: dev
    - stage: build
      script: ./tool/travis.sh command_1
      env: PKG="alryne_web"
      dart: dev
    - stage: unit_test
      script: ./tool/travis.sh test
      env: PKG="alryne_web"
      dart: dev
    - stage: unit_test
      script: ./tool/travis.sh command_2
      env: PKG="alryne_web"
      dart: dev

stages:
  - analyze
  - format
  - build
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
