dart:
  - dev

stages:
  - analyze:
    - dartanalyzer: --fatal-warnings --options=analysis_options.yaml .
  - format:
    - dartfmt: --dry-run --set-exit-if-changed .
  - unit_test:
    - command: pub run test