name: alryne
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Abhi Agarwal <email@example.com>

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  meta: '^1.1.2'
  json_annotation: '^0.2.2'
  quiver: '>=0.28.0 <0.29.0'
  collection: '^1.14.6'

dev_dependencies:
  build_runner: ^0.7.6
  json_serializable: '^0.3.2'
  test: ^0.12.0
