name: alryne
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Abhi Agarwal <email@example.com>

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dev_dependencies:
  test: ^0.12.0
