name: alryne_web
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: Abhi Agarwal <email@example.com>

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  angular: '^5.0.0-alpha+5'
  angular_components: '^0.9.0-alpha+5'

dev_dependencies:
  build_runner: ^0.7.8
  build_web_compilers: ^0.2.1
  angular_test: '^2.0.0-alpha+3'
  browser: ^0.10.0
  test: ^0.12.0

web:
  compiler:
    debug: dartdevc
